# Google Cloud Run configuration
runtime: nodejs18
service: gov-asset-tracker-backend
instance_class: F2

env_variables:
  PORT: 8080
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 2

# For Cloud SQL connection
vpc_access_connector:
  name: projects/gov-asset-tracker/connectors/default
